### ISSUE TITLE
Fail to run on local macos

### ISSUE THREAD

**Issue by kobofare** [0xTCG/sequre#11]
i try to compile llvm-project,codon on local machine, then execute command step by step as installation in readme.md, meet error

➜  sequre git:(develop) ✗ sequre examples/local_run.codon
ring.codon:804:1-4090: error: 'Tuple' does not match expected type 'Tuple[int,int]'
├─ he.codon:13:1-514: error: during the realization of <import sequre.lattiseq.ckks>
├─ env.codon:8:1-21: error: during the realization of <import sequre.mpc.he>
├─ runtime.codon:3:1-34: error: during the realization of <import sequre.mpc.env>
├─ __init__.codon:2:1-31: error: during the realization of <import sequre.runtime>
├─ hastings.codon:2:1-57: error: during the realization of <import sequre.__init__>
╰─ local_run.codon:1:1-27: error: during the realization of <import hastings>

macos version: 14.2
codon version: 0.16.3
llvm-config version: 15.0.1

**Comment by kobofare** [comment]
➜  sequre git:(develop) ✗ g++ --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by HarisSmajlovic** [comment]
The latest Codon is not compatible with Sequre. 

Use this fork:
`git clone --branch sequre https://github.com/HarisSmajlovic/codon.git`

**Comment by kobofare** [comment]
![image](https://github.com/0xTCG/sequre/assets/1838334/f94ed746-b2e9-4434-8ffc-58b186c753c6)
CPM version is too old

**Comment by kobofare** [comment]
worked.
![image](https://github.com/0xTCG/sequre/assets/1838334/8cc8b05d-9783-4973-98ae-cdf63fac08fe)

**Comment by kobofare** [comment]
I'm curious why not just submit the code directly to the codon repository, but fork a new repository.

**Comment by HarisSmajlovic** [comment]
The latest Codon cannot compile Sequre due to a compiler bug that needs to be fixed. We are working on it.

Btw. for faster runtime use release mode: `sequre -release examples/local_run.codon`

**Comment by kobofare** [comment]
May I ask, what is the next plan for the sequre computing framework.

**Comment by HarisSmajlovic** [comment]
Sure. We plan to add support for another privacy-enhancing technology and then add some missing pieces before releasing the first beta version.

**Comment by kobofare** [comment]
I have over ten years of programming experience and am familiar with various programming languages. Please let me know if there are any urgent matters that I can participate in.

**Comment by hsmajlovic** [comment]
Of course. I will come back to you with some details in the following days.

**Comment by hsmajlovic** [comment]
@kobofare I made some issues public. Feel free to skim through them and please don't hesitate to ask any questions.

**Comment by kobofare** [comment]
@hsmajlovic What IDE tool do you usually use to develop codon code.

**Comment by hsmajlovic** [comment]
Either VSC with python highlights or just plain vim.
